#!/bin/bash

cd /home/$USER/
mkdir .beefinstall
cd .beefinstall

git clone https://github.com/beefproject/beef
cd beef

./install

sleep 1
rm config.yaml
curl -o config.yaml https://jamisonsmith.is-a.dev/installers/config.yaml

echo "Default Password for beEF: 12345678"

./beef