#!/bin/bash

cd $HOME
mkdir .installertmp
cd .installertmp

curl -lso feet-command https://jamisonsmith.is-a.dev/scripts/FEet

chmod +x feet-command
sudo cp ./feet-command /usr/local/bin/feet
curl -lso feet-version https://jamisonsmith.is-a.dev/scripts/feet-version
cp ./feet-version $HOME/.pime/.feetversion
cd ..
rm -rf .installertmp

echo "Installed FEet, try to run the command 'feet' to work"