#!/bin/bash
netget() {
    url="$1"
    host=$(echo "$url" | sed -E 's_https?://([^/]+).*_\1_')
    path=$(echo "$url" | sed -E 's_https?://[^/]+(/.*)?_\1_')
    path=${path:-/}

    {
        echo "GET $path HTTP/1.1"
        echo "Host: $host"
        echo "User-Agent: pimenetget/1.0"
        echo "Connection: close"
        echo
    } | openssl s_client -quiet -connect "$host:443" 2>/dev/null |
        awk 'BEGIN {header=1} /^\r?$/ {header=0; next} !header'
}
cd $HOME
mkdir .installertmp
cd .installertmp

netget https://jamisonsmith.is-a.dev/scripts/pime > pime-command

chmod +x pime-command
sudo cp ./pime-command /usr/local/bin/pime
netget https://jamisonsmith.is-a.dev/scripts/pime-version > pime-version
cp ./pime-version $HOME/.pimeversion
cd ..
rm -rf .installertmp

echo "Installed pime, try to run the command 'pime' to work"